### PR TITLE
JENKINS-64375: Change "slave" to "agent"

### PR DESCRIPTION
**Pull request by ghost**
Changing `slaveWorkspacesUsage` to `agentWorkspacesUsage` in disk-usage.xml test resource for project1.

See [JENKINS-64375](https://issues.jenkins.io/browse/JENKINS-64375?jql=labels%20%3D%20newbie-friendly%20and%20status%20in%20(Open%2C%20%22To%20Do%22%2C%20Reopened)).

### CODE REVIEW

**Comment by ghost** [comment]
@v1v Can you take a look at this?

**Comment by v1v** [comment]
Thanks for your contribution, even though emails are accessible in the git history, I'd say please do not directly add it, I do not work anymore for that company. 

I'll enable the CI for this project firstly and then validate it in my end, so I'll let you know once I have done that

Thanks

**Comment by ghost** [comment]
Ok, was just following the guidelines on jenkins.io.  Thanks!

**Comment by ghost** [comment]
I'm closing this PR due to inactivity.

**Pull request closed without merging**
